- hosts: jenkins
  remote_user: ec2-user
  become: true
  vars:
    port: 7989
  tasks:
    - name: add jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'
    - name: add jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
    - name: install java and jenkins
      yum:
        name: "{{item}}"
        state: present
      loop:
        - fontconfig
        - java
        - jenkins
    - name: start httpd
      service:
        name: httpd
        enabled: true
        state: started
    - name: start jenkins
      service:
        name: jenkins
        enabled: true
        state: started
    - name: change the jenkins port
      lineinfile:
        path: /etc/sysconfig/jenkins
        regexp: "^JENKINS_PORT="
        line: JENKINS_PORT={{port}}
      notify:
        - restart jenkins
  handlers:
    - name: restart jenkins
      service:
        name: jenkins
        state: restarted