# We are going to install mysql, php

- hosts: all
  remote_user: ec2-user
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: "{{item}}"
        state: present
      loop:
        - httpd
        - mysql
        - php